import { type NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { signIn, signOut, useSession } from 'next-auth/react';

import { api } from '~/utils/api';
import LandingPage from '~/components/LandingPage';
import Footer from '~/components/footer';
import Menu from '~/components/Menu';

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: 'from tRPC' });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />
      <main className="flex min-h-screen flex-col items-center justify-center">
        <LandingPage />
      </main>
      <Footer />
    </>
  );
};

export default Home;
