-- AlterTable
ALTER TABLE `task` MODIFY `userId` VARCHAR(191) NULL,
    MODIFY `team` VARCHAR(191) NULL,
    MODIFY `createdAt` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `priority` ENUM('HIGH', 'MEDIUM', 'LOW') NULL DEFAULT 'LOW',
    MODIFY `DueDate` DATETIME(3) NULL;
